### ISSUE TITLE
Make a release to support Gradle 6

### ISSUE THREAD

**Issue by mustaine** [TNG/JGiven#441]
Would it be possible to make a release or a release candidate to be able to upgrade projects using Gradle plugin to the version 6?

**Comment by janschaefer** [comment]
Yes. I try to do it as soon as possible. I am struggled a bit with the Android Plugin.

**Comment by janschaefer** [comment]
@mustaine I just released version 1.0.0-RC1. I had some problems to get the Gradle Plugin working, so the Gradle Plugin itself now has version 1.0.0-RC1.4. Could you please test if it is working for you?

**Comment by mustaine** [comment]
I am gonna need to investigate as looks like there is some issue with the dependencies.

**Comment by mustaine** [comment]
I had problems with the jgiven-core, but looks like that gson should be exported now but does not seem to work with the 1.0.0-RC1

Can you do a clean RC for all the project?

**Comment by mustaine** [comment]
I dig a little bit more and the problem is in `jgiven-core` https://github.com/TNG/JGiven/blob/master/jgiven-core/build.gradle#L9

Looks like the RC2 is not with the latest changes. Can we try a new RC and I will give it a go?
Locally I tried a local release and works fine.

**Comment by mustaine** [comment]
Let me know once we have a new RC so I can verify it works fine for gradle 5 and 6

**Comment by mustaine** [comment]
Any update on it @janschaefer ?

**Comment by janschaefer** [comment]
Sorry, not yet. Will try to release something today.

**Comment by janschaefer** [comment]
@mustaine: I released 1.0.0-RC3

**Comment by mustaine** [comment]
I don't understand RC3 still have the dependency not coming

```
|    +--- com.tngtech.jgiven:jgiven-core:1.0.0-RC3
|    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.26
|    |    +--- com.thoughtworks.paranamer:paranamer:2.8
|    |    +--- net.bytebuddy:byte-buddy:1.10.3
|    |    \--- org.fusesource.jansi:jansi:1.15
```

But if use a local build with master, then it comes 🤔

**Comment by mustaine** [comment]
Looking at the `pom.xml` release looks like is missing the dependencies
https://repo1.maven.org/maven2/com/tngtech/jgiven/jgiven-core/1.0.0-RC3/jgiven-core-1.0.0-RC3.pom

**Comment by mustaine** [comment]
@janschaefer would you be able to investigate and validate if locally you get the deps?

**Comment by janschaefer** [comment]
It is really strange. When publishing locally it works as expected. When uploading to Nexus the dependencies are missing...

**Comment by janschaefer** [comment]
Ok. This seems to be a known issue. https://github.com/gradle/gradle/issues/6438

**Comment by janschaefer** [comment]
The issue should be fixed. Please try with 1.0.0-RC4.
